// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "time"

type GenerateDefaults struct {
	// Count corresponds to the JSON schema field "count".
	Count int `json:"count,omitempty" yaml:"count,omitempty" mapstructure:"count,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Nested corresponds to the JSON schema field "nested".
	Nested *Nested `json:"nested,omitempty" yaml:"nested,omitempty" mapstructure:"nested,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout time.Duration `json:"timeout,omitempty" yaml:"timeout,omitempty" mapstructure:"timeout,omitempty"`
}

// GenerateDefaultsDefault returns the default values for GenerateDefaults.
func GenerateDefaultsDefault() GenerateDefaults {
	var plain GenerateDefaults
	plain.Count = 42.0
	plain.Enabled = true
	plain.Name = "hello"
	defaultNested := NestedDefault()
	plain.Nested = &defaultNested
	plain.Tags = []string{
		"a",
		"b",
	}
	if v, err := time.ParseDuration("1m30s"); err != nil {
		panic(err)
	} else {
		plain.Timeout = v
	}
	return plain
}

type Nested struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label,omitempty" yaml:"label,omitempty" mapstructure:"label,omitempty"`
}

// NestedDefault returns the default values for Nested.
func NestedDefault() Nested {
	var plain Nested
	plain.Label = "nested-default"
	return plain
}
